---
# defaults file for deluge-web-docker
port: 8112

data_directory: /data/deluge-web

torrent_directory: /data/torrent
folder_owner: root
folder_group: root
folder_mode: 0770

# place web.conf in the templates folder and switch this to true to restore config
config_exist: false
