---
# tasks file for starbound-docker
- name: Creating data directory
  file:
    path: "{{ data_directory }}"
    state: directory
    recurse: yes

- name: Deploying starbound container
  docker:
    name: starbound
    image: lacsap/starbound
    state: reloaded
    pull: always
    restart_policy: always
    ports:
      - "{{ port }}:21025"
    env:
      STEAM_USERNAME: "{{ steam_username }}"
      STEAM_PASSWORD: "{{ steam_password }}"

    volumes:
      - "{{ data_directory }}:/server/steamcmd/starbound"
