---
# tasks file for startpage-docker
- name: Deploying startpage container
  docker:
    name: startpage
    image: lacsap/startpage
    state: restarted
    pull: always
    ports:
      - "{{ port }}:80"
