---
# tasks file for deluge-web

- name: Install Deluge-web and deluged
  apt: name={{ item }} state=latest
  with_items:
   - deluge-web
   - deluged

- name: Create systemd deluged service file
  template: src=deluged.service.j2 dest=/etc/systemd/system/deluged.service

- name: Create systemd deluge-web service file
  template: src=deluge-web.service.j2 dest=/etc/systemd/system/deluge-web.service

- name: Add deluge group
  group:
    name: "{{deluge_group}}"
    state: present

- name: Add deluge user
  user:
    name: "{{deluge_user}}"
    group: "{{deluge_user}}"
    system: yes
    state: present

- name: Start and enable deluged
  service:
    name: deluged
    enabled: yes
    state: started

- name: Start and enable deluge-web
  service:
    name: deluge-web
    enabled: yes
    state: started
