---
- name: Install everything
  hosts: dev
  sudo: yes

- include: deluge-web-docker.yml
- include: dokuwiki-docker.yml
- include: owncloud-docker.yml
- include: quassel-core-docker.yml
- include: startpage-docker.yml
- include: samba.yml
