---
#example playbook
- name: Test docker
  hosts: test
  sudo: yes
  tasks:
    - name: install pip
      apt: >
        name=python-setuptools
        state=present
        update_cache=yes

    - name: install pip
      easy_install: >
        name=pip

    - name: "test docker py"
      pip: >
        name=docker-py
        state=present
